application: yaelsprikut
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts
  
- url: /less
  static_dir: less
  
- url: /font-awesome
  static_dir: font-awesome
  
- url: /home/font/(.*\.otf)
  static_files: home/font/\1
  upload: home/font/(.*\.otf)
  mime_type: application/x-font-otf

- url: /img/(.*\.(gif|png|jpg))$
  static_files: img/\1    
  upload: img/.*\.(gif|png|jpg)$

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.pdf)
  mime_type: application/pdf
  static_files: static/\1
  upload: static/(.*\.pdf)
  
# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: index.php

- url: /index\.html
  script: index.php
  
  


